function lab = GetSegmentSaliencyLabel( gtmask, superpixel, spNum, thresh)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% version1:
% gtmask    ground truth of the PIXEL_WISE annotation
% imdata    generated by the getImData
% splabel   the label of the superpixels, coming from multi segmentation
% segment   segment = unique(splabel)
% lab       {-1, 0, 1} -1 is background, 1 is the salient object, 
%           and 0 is uncertain
% 
% version2:
% superpixel  regions created by SLIC
% spNum       the number of superpixels
% thresh      the gt pixels in superpixel
% 只返回两种标签 -1 1
% zxforchid@163.com
% written by xiaofei zhou,shanghai university,shanghai, china
% 2016/1/11
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     thresh = 0.75;
    
    gtmask(gtmask >= 128) = 255;
    gtmask(gtmask < 128) = 0;
    gtmask = double(gtmask);
    
    spstats = regionprops( superpixel, 'PixelIdxList' );
    
    nseg = spNum;
    
    lab = zeros( nseg, 1 );
    
    for ix = 1 : nseg
        pixels = spstats(ix).PixelIdxList;
        [saliency, occurence] = mode( gtmask(pixels) ); % occurence指出现的最高次数
        gtRate = occurence / max(length(pixels), eps);
        if ( gtRate > thresh) && (saliency == 255)
               lab(ix) = 1;
        else
               lab(ix) = -1;
        end
%         if occurence / max(length(pixels), eps) < thresh
%             lab(ix) = 0;
%         else
%             if saliency == 255
%                 lab(ix) = 1;
%             elseif saliency == 0
%                 lab(ix) = -1;
%             else
%                 error( 'error in gtmask' );
%             end
%         end
    end
    
    
    clear gtmask superpixel spNum thresh
end